[build]
  command = "echo \"No build step required\""
  publish = "."

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/import-products"
  to = "/.netlify/functions/import-products"
  status = 200
